name: CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: golang:1.13.0-alpine3.10
    steps:
    - name: APK Update so we have the tools we need
      run: apk add make --no-cache

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: List Current Directory
      run: ls

    - name: Install tools needed by the project
      run: make tools

    - name: Check Go Version
      run: make version

    - name: Runs go env
      run: make environment

    - name: Runs go test -v -cover ./..
      run: make test

    - name: Runs go golangci-lint run ./..
      run: make lint

    - name: Install tools needed by the project
      run: make build

    - name: Report code tests coverage, and check
      run: make coverage


  # test:
  #   name: Test
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:

  #   - name: Login Docker Registry
  #     env:
  #       DOCKER_REGISTRY_URL: docker.pkg.github.com
  #       DOCKER_USERNAME: ${{ github.actor }}
  #       DOCKER_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
  #     run: echo $DOCKER_PASSWORD | docker login $DOCKER_REGISTRY_URL --username $DOCKER_USERNAME --password-stdin

  #   # - name: Use jmuldoon/docker/go-ci v0.0.2
  #   #   env:
  #   #     DOCKER_REGISTRY_URL: docker.pkg.github.com
  #   #     DOCKER_USERNAME: ${{ github.actor }}
  #   #     DOCKER_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
  #   #   uses: docker://docker.pkg.github.com/jmuldoon/docker/go-ci:0.0.2


  #   - name: Check out code into the Go module directory
  #     uses: actions/checkout@v1

  #   - name: Check Go Version
  #     run: go version

  #   - name: Check Go Env
  #     run: go env

  #   - name: Runs go golangci-lint run ./..
  #     run: make lint

  #   - name: Report code tests coverage, and check
  #     run: make coverage
