name: CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    # - name: Login Docker Registry
    #   env:
    #     DOCKER_REGISTRY_URL: docker.pkg.github.com
    #     DOCKER_USERNAME: ${{ github.actor }}
    #     DOCKER_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
    #   run: echo $DOCKER_PASSWORD | docker login $DOCKER_REGISTRY_URL --username $DOCKER_USERNAME --password-stdin

    # - name: Use golang dockerhub image v1.13.0-alpine3.10
    #   uses: docker://golang:1.13.0-alpine3.10

    - name: Use jmuldoon/docker/go-ci v0.0.2
      env:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      uses: docker://docker.pkg.github.com/jmuldoon/docker/go-ci:0.0.2

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: List Current Directory
      run: ls

    - name: Install tools needed by the project
      run: make tools

    - name: Install tools needed by the project
      run: make build

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Login Docker Registry
      env:
        DOCKER_REGISTRY_URL: docker.pkg.github.com
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      run: echo $DOCKER_PASSWORD | docker login $DOCKER_REGISTRY_URL --username $DOCKER_USERNAME --password-stdin

    # - name: Use jmuldoon/docker/go-ci v0.0.2
    #   env:
    #     DOCKER_REGISTRY_URL: docker.pkg.github.com
    #     DOCKER_USERNAME: ${{ github.actor }}
    #     DOCKER_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
    #   uses: docker://docker.pkg.github.com/jmuldoon/docker/go-ci:0.0.2


    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Check Go Version
      run: go version

    - name: Check Go Env
      run: go env

    - name: Runs go golangci-lint run ./..
      run: make lint

    - name: Report code tests coverage, and check
      run: make coverage
